### ISSUE TITLE
Getting error while installing in Python 3.9.6

### ISSUE THREAD

**Issue by chaitanya-smartrotamac** [SunitRaut/pyMultiSerial#6]
pip install pyMultiSerial
Collecting pyMultiSerial
  Using cached pyMultiSerial-1.1.0-py3-none-any.whl (17 kB)
Requirement already satisfied: pyserial in c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages (from pyMultiSerial) (3.5)
Note: you may need to restart the kernel to use updated packages.
ERROR: Could not find a version that satisfies the requirement threading (from pymultiserial) (from versions: none)
ERROR: No matching distribution found for threading

**Comment by SunitRaut** [comment]
The library threading is not available in Python 2, So it won't be installed with pip command.
Please try installing the pyMultiSerial library again with pip3 command instead of pip.
Kindly let us know if it works. 
Thanks.

**Comment by SunitRaut** [comment]
This issue has now been solved in release 1.1.1.
Please reinstall the module.
