### ISSUE TITLE
Error occuring during the installation of pyMultiSerial

### ISSUE THREAD

**Issue by Zubbyzer** [SunitRaut/pyMultiSerial#7]
I have tried a lot of things trying to solve these errors but i keep getting them while trying to install pyMultiSerial.
ERROR: Could not find a version that satisfies the requirement threading (from pymultiserial) (from versions: none)
ERROR: No matching distribution found for threading

**Comment by SunitRaut** [comment]
The library threading is not available in Python 2, So it won't be installed with pip command.
Please try installing the pyMultiSerial library again with pip3 command instead of pip. 
Kindly let us know if it works.
Thanks.

**Comment by Zubbyzer** [comment]
I used the pip3 command, tried on 2 different pcs without the same setup and it didn't work on any. Tried to install through conda too, didn't work.Thx for trying to help.-------- Message original --------De : Sunit Raut ***@***.***>Date : mer. 25 mai 2022 à 19:43À : SunitRaut/pyMultiSerial ***@***.***>Cc : Zubbyzer ***@***.***>, Author ***@***.***>Objet : Re: [SunitRaut/pyMultiSerial] Error occuring during the installation of pyMultiSerial (Issue #7)
The library threading is not available in Python 2, So it won't be installed with pip command.
Please try installing the pyMultiSerial library again with pip3 command instead of pip.
Kindly let us know if it works.
Thanks.

**Comment by SunitRaut** [comment]
Hello Zubbyzer,
As a workaround, you can download this python script and save it as pyMultiSerial.py: 
https://github.com/SunitRaut/pyMultiSerial/blob/main/src/pyMultiSerial/__init__.py

Then import it into your script using statement: 
from pyMultiSerial import pyMultiSerial as p. 

With this you can start using this module immediately.

**Comment by Zubbyzer** [comment]
Thanks a lot, I'm gonna try this out

**Comment by Zubbyzer** [comment]
I think I have succefully imported it into my script but I'm actually struggling on the comprehension on how I should write the script using pyMultiSerial, could you send me a exemple of a simple script reading the data coming from a serial port. Thanks again.

**Comment by SunitRaut** [comment]
Hi, 

You can use this script as an example:
https://github.com/SunitRaut/pyMultiSerial/blob/main/Examples/1.Reading_from_All_Ports_Simultaneously.py

**Comment by rdfrost** [comment]
> Hello Zubbyzer, As a workaround, you can download this python script and save it as pyMultiSerial.py: https://github.com/SunitRaut/pyMultiSerial/blob/main/src/pyMultiSerial/__init__.py
> 
> Then import it into your script using statement: from pyMultiSerial import pyMultiSerial as p.
> 
> Make sure to save both scripts in same folder.
> 
> With this you can start using this module immediately.

Results in error:
`ImportError: cannot import name 'pyMultiSerial' from 'pyMultiSerial' (./pyMultiSerial.py)`

Using the following works:
`import pyMultiSerial as p`

**Comment by SunitRaut** [comment]
This issue has now been solved in release 1.1.1.
Please reinstall the module.
